### ISSUE TITLE
TOC Scrolltrigger not working 

### ISSUE THREAD

**Issue by olpo24** [Wolfi1616/Bricks-Tutorial-Elements#2] opened 2022-10-07 07:41 UTC
Hi Wolfgang,

in my case (I don't know if I doing anything wrong) the scrolltrigger feature does not working well.

Only the fist item of the toc is highlighted. It doesn't matter which item is clicked.

What is curious is that the class "wcd_tableOfContents_active" is added to the correct item in the source code.

I'm using latest bricks 1.5.4.

Any Idea?

Kind regards,
Ole

**Comment by Wolfi1616** [comment] 2022-10-09 18:26
Hey Ole
that's weird. Obviously if the classes are placed correctly the javascript part is working fine. Did you also use the styles I've delivered with `wp_enqueue_style('wcd_toc_css');`? 

It's hard to debug without any link or further Information. So anything you could add here would be very helpful to find where the problem occurs! 

TIA
Cheers

**Comment by olpo24** [comment] 2022-10-10 06:58
Hey Wolfgang,

thanks for reply.

You can see a test here https://olpo.de/dev/real-cookie-banner-wird-3-rabatt-alarm/

Let me know what further informations do you need.

If it is easier for you, you can reach me also via mail wp[@]olpo.de

Thanky you very much.

Ole

**Comment by olpo24** [comment] 2022-10-10 07:02
if it is important information: I use yout toc solution in a single blog template.

**Comment by Wolfi1616** [comment] 2022-10-10 07:07
Hey Ole, 
thanks a lot for sharing the link. I've tested the site and the classes get applied on scroll correctly (see screenshot). The Problem is, that your TOC is not sticky or fixed on the site so you don't see anything happen.

The first element get's auto highlighted when you scroll to it's position, that's why your first element isn't highlighted on initial page load. It's more about layout and not about the code, which is for me another issue. I'm gonna close that comment here and send you an email to help you put everything in place (but again, which is not really related to the code ;-)). 

Cheers

![Bildschirmfoto 2022-10-10 um 09 03 54](https://user-images.githubusercontent.com/75800215/194813477-629053cb-b90e-4183-be62-0f61d595dd3a.png)

**Closed** 2022-10-10 07:14 UTC
